name: Deploy Jira Plugin

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      JIRA_URL: http://your-jira-server:8080
      PLUGIN_FILE: target/hello-jira-1.0.0.jar
      JIRA_USER: ${{ secrets.JIRA_USER }}
      JIRA_PASS: ${{ secrets.JIRA_PASS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 8 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install Atlassian SDK
        run: |
          wget https://product-downloads.atlassian.com/software/atlassian-sdk/atlassian-plugin-sdk-latest.tar.gz
          tar -xzf atlassian-plugin-sdk-latest.tar.gz
          echo "$PWD/atlassian-plugin-sdk-*" >> $GITHUB_PATH

      - name: Build plugin with Atlassian Maven (atlas-mvn)
        # The Atlassian SDK sets up the correct Maven settings and plugin repos for you
        run: |
          export PATH="$PWD/atlassian-plugin-sdk-*/bin:$PATH"
          atlas-mvn --version
          atlas-mvn clean package

      # Adjust PLUGIN_FILE path according to the artifact actually built
      - name: Upload plugin to Jira
        run: |
          echo "Uploading plugin to $JIRA_URL"
          curl -u "$JIRA_USER:$JIRA_PASS" \
            -X POST \
            -H "Content-Type: multipart/form-data" \
            -F "plugin=@$PLUGIN_FILE" \
            "$JIRA_URL/rest/plugins/1.0/"
