name: Build and Deploy Jira Plugin

on:
  workflow_dispatch: # manual trigger from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      JIRA_URL: http://your-jira-server:8080
      PLUGIN_FILE: target/hello-jira-1.0.0.jar
      JIRA_USER: ${{ secrets.JIRA_USER }}
      JIRA_PASS: ${{ secrets.JIRA_PASS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 8 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'

      - name: Install Atlassian SDK
        uses: rodrigo-nogues/github-action-install-atlassian-sdk@v1
        # This action installs Atlassian SDK and adds it to PATH

      - name: Verify Atlassian SDK installation
        run: |
          atlas-version
          atlas-mvn --version

      - name: Build plugin with Atlassian Maven (atlas-mvn)
        run: atlas-mvn clean package -U


      - name: Verify plugin artifact exists
        run: |
          echo "Listing plugin artifact $PLUGIN_FILE"
          ls -l $PLUGIN_FILE

      - name: Upload plugin to Jira
        run: |
          echo "Uploading plugin to $JIRA_URL"
          curl -v -u "$JIRA_USER:$JIRA_PASS" \
            -X POST \
            -H "Content-Type: multipart/form-data" \
            -F "plugin=@$PLUGIN_FILE" \
            "$JIRA_URL/rest/plugins/1.0/"
